"""initial schema

Revision ID: c23ff31db2e4
Revises:
Create Date: 2026-08-16 20:33:09.515649

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c23ff31db2e4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fallback_messages",
        sa.Column("topic_code", sa.String(length=64), nullable=False),
        sa.Column("type", sa.Enum("COMPLIMENT", "SUPPORT", name="message_type"), nullable=False),
        sa.Column(
            "address_mode", sa.Enum("INFORMAL", "FORMAL", name="address_mode"), nullable=False
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("semantic_key", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fallback_messages")),
    )
    op.create_table(
        "prompt_versions",
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("system_prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint("version", name=op.f("uq_prompt_versions_version")),
    )
    op.create_table(
        "qualities",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qualities")),
        sa.UniqueConstraint("code", name=op.f("uq_qualities_code")),
    )
    op.create_table(
        "topics",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint("code", name=op.f("uq_topics_code")),
    )
    op.create_table(
        "users",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ONBOARDING", "ACTIVE", "PAUSED", "BLOCKED", name="user_status"),
            nullable=False,
        ),
        sa.Column(
            "onboarding_step",
            sa.Enum(
                "CONSENT",
                "ADDRESS_MODE",
                "QUALITIES",
                "TOPICS",
                "SUPPORT_PREFERENCES",
                "BLOCKED_TOPICS",
                "STYLE_EXAMPLES",
                "TIMEZONE",
                "SCHEDULE",
                "SUMMARY",
                "DONE",
                name="onboarding_step",
            ),
            nullable=True,
        ),
        sa.Column(
            "address_mode", sa.Enum("INFORMAL", "FORMAL", name="address_mode"), nullable=True
        ),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("is_adult_confirmed", sa.Boolean(), nullable=False),
        sa.Column("privacy_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_chat_id", name=op.f("uq_users_telegram_chat_id")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_users_telegram_user_id")),
    )
    op.create_table(
        "blocked_topics",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("topic_code", sa.String(length=64), nullable=True),
        sa.Column("custom_text", sa.Text(), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_blocked_topics_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blocked_topics")),
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("support_description", sa.Text(), nullable=True),
        sa.Column("sensitive_input_present", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_profiles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_profiles")),
    )
    op.create_table(
        "schedules",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.Enum("EXACT", "PERIOD", name="schedule_mode"), nullable=False),
        sa.Column("exact_local_time", sa.Time(), nullable=True),
        sa.Column(
            "period", sa.Enum("MORNING", "DAY", "EVENING", name="schedule_period"), nullable=True
        ),
        sa.Column("timezone_name", sa.String(length=64), nullable=False),
        sa.Column("fixed_utc_offset_minutes", sa.Integer(), nullable=True),
        sa.Column("next_run_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_sent_local_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_schedules_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
        sa.UniqueConstraint("user_id", name=op.f("uq_schedules_user_id")),
    )
    op.create_table(
        "style_examples",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("ONBOARDING", "LIKED_MESSAGE", name="style_example_source"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_style_examples_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_style_examples")),
    )
    op.create_table(
        "support_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("preference_code", sa.String(length=64), nullable=True),
        sa.Column("custom_text", sa.Text(), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("excluded_from_generation", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_support_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_preferences")),
    )
    op.create_table(
        "user_qualities",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("quality_id", sa.UUID(), nullable=True),
        sa.Column("custom_text", sa.Text(), nullable=True),
        sa.Column("is_sensitive", sa.Boolean(), nullable=False),
        sa.Column("excluded_from_generation", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quality_id"],
            ["qualities.id"],
            name=op.f("fk_user_qualities_quality_id_qualities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_qualities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_qualities")),
    )
    op.create_table(
        "user_topics",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_user_topics_topic_id_topics"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_topics_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_topics")),
        sa.UniqueConstraint("user_id", "topic_id", name="uq_user_topics_user_topic"),
    )
    op.create_table(
        "deliveries",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("local_delivery_date", sa.Date(), nullable=False),
        sa.Column("planned_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "GENERATING",
                "READY",
                "SENDING",
                "SENT",
                "FAILED",
                "EXPIRED",
                name="delivery_status",
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("fk_deliveries_schedule_id_schedules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_deliveries_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_deliveries_idempotency_key")),
        sa.UniqueConstraint("user_id", "local_delivery_date", name="uq_deliveries_user_local_date"),
    )
    op.create_table(
        "generated_messages",
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("type", sa.Enum("COMPLIMENT", "SUPPORT", name="message_type"), nullable=False),
        sa.Column("theme", sa.String(length=64), nullable=False),
        sa.Column("semantic_key", sa.String(length=255), nullable=False),
        sa.Column("source", sa.Enum("AI", "FALLBACK", name="message_source"), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("prompt_version_id", sa.UUID(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("validation_status", sa.String(length=32), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("text_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
            name=op.f("fk_generated_messages_delivery_id_deliveries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_generated_messages_prompt_version_id_prompt_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_generated_messages_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_messages")),
        sa.UniqueConstraint("delivery_id", name=op.f("uq_generated_messages_delivery_id")),
    )
    op.create_table(
        "feedback",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "reaction",
            sa.Enum("LIKED", "REPEATED", "DISLIKED", name="reaction_type"),
            nullable=False,
        ),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["generated_messages.id"],
            name=op.f("fk_feedback_message_id_generated_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_feedback_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
        sa.UniqueConstraint("message_id", name=op.f("uq_feedback_message_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback")
    op.drop_table("generated_messages")
    op.drop_table("deliveries")
    op.drop_table("user_topics")
    op.drop_table("user_qualities")
    op.drop_table("support_preferences")
    op.drop_table("style_examples")
    op.drop_table("schedules")
    op.drop_table("profiles")
    op.drop_table("blocked_topics")
    op.drop_table("users")
    op.drop_table("topics")
    op.drop_table("qualities")
    op.drop_table("prompt_versions")
    op.drop_table("fallback_messages")
    # ### end Alembic commands ###
